# ensure PHP versin 7.2 is installed
- name: ensure PHP 7.2 is installed
    command: 'php --version | head -n 1 |cut -d" " -f 2'
    changed_when: {{ installed_php_version <= "5" }}
    failed_when: False
    tags: neos_php
    register: installed_php_version
    when: "installed_php_version.exits"

# Installs compose https://getcomposer.org/download/
- name: Installing php compose
  command: php composer-setup.php --install-dir=/bin --filename=composer.phar

# Installes neos
- name: Installs Neos
  composer:
    command: create-project
    arguments: neos/neos-base-distribution neos-example
    working_dir: "{{ NEOS_WORKING_DIR }}"
    prefer_dist: yes



# Starts neos. Schuld be use systemd in a new Role version
- name: Start Neos server
  command: ./flow server:run
  register: init_neos_start
  {{ NEOS_WORKING_DIR }}
